### ISSUE TITLE
Add votes and reputation gain to user profile's activity

### ISSUE THREAD

**Issue by Miragide** [CaptainFact/captain-fact#116]
## Idée
> RestInPeaces sur discord
Il est vrais que dans la section activité du site, il y à un certain historique.
Mais rien ne trace réellement l'évolution de nos point de réputation.
De plus il y à pas vraiment mention dans "https://captainfact.io/help/reputation" du temp de "pending" pour attribuer ces points.

Pour améliorer la compréhension des points de réputation, la gamification et la motivation qu'ils confèrent : mentionner les gains et les pertes de points dans les onglets profil des membres.

## Proposition de design : 
![cf-comments-notes](https://user-images.githubusercontent.com/15331478/67965305-1db44b80-fc02-11e9-8a30-05adf50ed9f8.jpg)

## Textes
FR
- Vote positif reçu [...]
- Vote négatif reçu [...]

EN
- Up vote received 
- Down vote received

## Note au développeur
- De préférence mettre les (+) et le (-) présents dans les labels de réputation en **gras** pour améliorer leur lisibilité

## Autre
Les gains de réputation devraient être notifiés.

**Comment by Betree** [comment]
I started working on this since it was strongly related to the changes I've made to store the reputation in the history.

I still need to add the descriptions for actions that were not previously displayed, but it's mostly done.

The main challenge I faced is to provide a clear visual distinction between the actions you authored and the ones that targeted you. We'll probably need to follow-up with a design update!
