### ISSUE TITLE
Action daily limit doesn't take into account the undo

### ISSUE THREAD

**Issue by balkhmogaehild** [CaptainFact/captain-fact#31]
When you are are a new user, if you undo an action (like undoing an _upvote_) it still count as a action so you can reach the daily limit without any effective action (you can undo all you _upvote_ without being able to do another one).

**Comment by Betree** [comment]
Since https://github.com/CaptainFact/captain-fact-api/pull/98 limitations are based on a 15 minutes period instead of 24h so in most cases the action limiter is transparent to the user. The need for this issue is now not high enough in regard of the cost of implementing it.

Thanks for the suggestion @balkhmogaehild, please contribute again in the future - this kind of issues help us to see where we need to improve :slightly_smiling_face:
