### ISSUE TITLE
Reward statement collectors

### ISSUE THREAD

**Issue by Vayel** [CaptainFact/captain-fact#59]
Collecting statements from a video (with the feature "Add a statement") is indispensable for fact-checking but is not rewarded. We should probably change.

To avoid having people collect statements that are not fact-checkable, I can see two methods:

* A statement can be downvoted (different from refuted) by the community to say that it's not relevant
* The reputation for having collected a statement is only gained when a comment with a source is posted

**Comment by Betree** [comment]
This is a really important topic. It's a shame that users that participate to the fastidious task of transcribing statements doesn't get rewarded today, especially since some users really spend a lot of time to make them good.

I've added this to the roadmap so we'll make a clear plan to move forward with this.

**Comment by Miragide** [comment]
move to: https://github.com/CaptainFact/captain-fact/issues/69
